spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/impact_design?useUnicode=true&characterEncoding=utf8mb4
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: false

file:
  base-url: http://iptdesign.mycafe24.com/uploads

jwt:
  secret: ${JWT_SECRET}

openai:
  api-key: ${OPENAI_API_KEY}

cors:
  allowed-origins: http://iptdesign.mycafe24.com
