spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/impact_design?useUnicode=true&characterEncoding=utf8mb4
    username: root
    password: Rnqhstlr!23

jwt:
  secret: mysecretkey12345asdfvasdfvhjaaaaaaaaaaaaaaaaaaaaaaaaaslfdjasdlkr231243123412

openai:
  api-key: sk-proj-ug8F8LTp9IGhABt2oAviT3BlbkFJaS7ggavlvRUQ6g5LuvvA

file:
  base-url: http://localhost:8080/uploads

cors:
  allowed-origins: http://localhost:3000
