spring:
  application:
    name: Impact_design
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET}
  access-expiration: 3600000
  refresh-expiration: 604800000

openai:
  api-key: ${OPENAI_API_KEY}
  base-url: https://api.openai.com/v1

file:
  storage: local
  upload-dir: ./uploads

